name: Diagram generation

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'requirements/**.txt'
      - '.github/workflows/diagram.yml'
      - 'themes/**'
      - '.gitmodules'

jobs:
  call-another-reusable:
    uses: eol-uchile/edx-staging/.github/workflows/diagram.yml@eol-release/koa
