name: Docker Image CI

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - virtuallabx-release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  variables:
    uses: eol-uchile/edx-platform/.github/workflows/variables.yml@eol/koa.master
  build:
    needs: [ variables ]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TS: ${{ needs.variables.outputs.timestamp }}
      RELEASE-NAME: ${{ needs.variables.outputs.release-name }}

    steps:
      - uses: actions/checkout@v4

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build OpenedX
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:${{ env.RELEASE-NAME }} --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:${{ env.RELEASE-NAME }}-${{ env.TS }} --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:${GITHUB_SHA} --target base

      - name: Build Static files for OpenedX S3
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${{ env.RELEASE-NAME }} --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${{ env.RELEASE-NAME }}-${{ env.TS }} --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${GITHUB_SHA} --target s3

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'merge_group' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:${{ env.RELEASE-NAME }}
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:${{ env.RELEASE-NAME }}-${{ env.TS }}
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:${GITHUB_SHA}
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${{ env.RELEASE-NAME }}
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${{ env.RELEASE-NAME }}-${{ env.TS }}
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${GITHUB_SHA}

  webhook:
      needs: [ variables, build ]
      if: ${{ github.event_name == 'merge_group' }}
      uses: ./.github/workflows/webhook.yml
      secrets: inherit

