name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'requirements/*.txt'
      - 'themes/**'

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build OpenedX
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:${GITHUB_SHA} --target base

      - name: Build Static files for OpenedX S3
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${GITHUB_SHA} --target s3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: |
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:${GITHUB_SHA}
          docker push ghcr.io/eol-virtuallabx/virtuallabx-edx:s3-static-${GITHUB_SHA}

