name: Webhook Update Virtuallabx

on:
  workflow_call:
    secrets:
      WEBHOOK_SECRET:
        required: true
  repository_dispatch:
    types: [debug-webhook]

jobs:
  webhook:
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} == 'workflow_call' || ${{ github.event.client_payload.debug }}
    steps:
      - name: Trigger argoCD repository workflow
        run: |
            curl --fail-with-body --silent -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-virtuallabx/edx-argocd/dispatches --data '{"event_type": "update-images", "client_payload": {"flavour": "virtuallabx"}}'
